### PR TITLE
Exposes MMAL_PARAM_FLICKERAVOID_T to the config file.

### PR DESCRIPTION
**Pull request by heathbarpunch**
I needed flickeravoid exposed to avoid flicker in some low light situations on Pi4 with HQ camera.

### CODE REVIEW

**Comment by rf152** [comment]
That's a good start, but by the looks of things you've not applied the flickeravoid to the actual camera object. You've got the code to pull it in from the config file, but you need to apply it to the mmal session. See 478-485 for how it pulls in and applies the mirror mode.

**Comment by heathbarpunch** [comment]
Oh I see what you mean I'll take another crack at this today. 

Edit: Okay this did raise another question for me: I don't understand how the if ( mmal_port_parameter_set()){}... section actually works.

Is it basically cycling through trying to register on output control ports 0-2 and if it can't it reports that it failed to set the parameter? If so that totally makes sense and the part that is confusing me is: why 3 ports? because that was a sufficient count for the amount of controls that were attempting to communicate on the output ports?

**Comment by rf152** [comment]
Sorry, which bit are you looking at and are confused? Could you give me a line number?

**Comment by heathbarpunch** [comment]
480-483 in the the base branch:

```
if (    mmal_port_parameter_set(camera->output[0], &mirror.hdr) != MMAL_SUCCESS ||
            mmal_port_parameter_set(camera->output[1], &mirror.hdr) != MMAL_SUCCESS ||
            mmal_port_parameter_set(camera->output[2], &mirror.hdr))
```

What I don't understand is why you are doing an 'or' between 3 possible camera->output ports when it seems like you only have 2 sections of code that use the output control ports: Mirror and Rotation. 

Meanwhile when I added:

```
MMAL_PARAMETER_FLICKERAVOID_T flickeravoid = {{MMAL_PARAMETER_FLICKER_AVOID, sizeof(MMAL_PARAMETER_FLICKERAVOID_T)}, getFlickerAvoidMode()};
if (    mmal_port_parameter_set(camera->output[0], &flickeravoid.hdr) != MMAL_SUCCESS ||
        mmal_port_parameter_set(camera->output[1], &flickeravoid.hdr) != MMAL_SUCCESS ||
        mmal_port_parameter_set(camera->output[2], &flickeravoid.hdr))
    {
        std::cout << "Failed to set flicker avoid parameter." << std::endl;
    }
```

I consistently get 'Failed to set flicker avoid parameter.' so it seems like I either need to use a different type of control port for Flicker Avoid or I need to add an additional output control port number to try and connect to. 

Edit: Nevermind. figured it out and updated here.

**Pull request merged**
